local storage = require("review-comments.storage")

describe("review-comments.storage", function()
  describe("get_storage_path", function()
    it("returns project-scoped json path", function()
      local path = storage.get_storage_path()
      assert.is_not_nil(path)
      assert.truthy(path:match("/review%-comments/[%x]+%.json$"))
    end)

    it("uses a stable path for the same project", function()
      local first = storage.get_storage_path()
      local second = storage.get_storage_path()
      assert.equals(first, second)
    end)
  end)
end)
